name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Build
        run: go build -v ./...

      - name: Test
        run: ENV=dev DB_HOSTNAME=mysql DB_USERNAME=root DB_PASSWORD=password DB_DATABASE=testdb CGO_ENABLED=0 go test ./... --count=1 -p=1